# Generated by Django 5.0.1 on 2025-04-23 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PokemonAbility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('is_hidden', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Pokemon abilities',
            },
        ),
        migrations.CreateModel(
            name='PokemonType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pokemon',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('height', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('sprite_front_default', models.URLField(blank=True, null=True)),
                ('sprite_back_default', models.URLField(blank=True, null=True)),
                ('sprite_front_shiny', models.URLField(blank=True, null=True)),
                ('sprite_back_shiny', models.URLField(blank=True, null=True)),
                ('sprite_official_artwork', models.URLField(blank=True, null=True)),
                ('hp', models.IntegerField(default=0)),
                ('attack', models.IntegerField(default=0)),
                ('defense', models.IntegerField(default=0)),
                ('special_attack', models.IntegerField(default=0)),
                ('special_defense', models.IntegerField(default=0)),
                ('speed', models.IntegerField(default=0)),
                ('is_favorite', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('abilities', models.ManyToManyField(related_name='pokemon', to='pokedex.pokemonability')),
                ('types', models.ManyToManyField(related_name='pokemon', to='pokedex.pokemontype')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
    ]
